# 수중 음파 탐지기(sonar) 데이터 셋
- Sonar 데이터 셋을 이용해서 Mines와 Rocks를 구분하는 모델 만들기


In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression #분류 
from sklearn.model_selection import train_test_split

In [3]:
sonar = pd.read_csv('sonar_csv.csv')

In [4]:
sonar

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0         0.0200       0.0371       0.0428       0.0207       0.0954   
1         0.0453       0.0523       0.0843       0.0689       0.1183   
2         0.0262       0.0582       0.1099       0.1083       0.0974   
3         0.0100       0.0171       0.0623       0.0205       0.0205   
4         0.0762       0.0666       0.0481       0.0394       0.0590   
..           ...          ...          ...          ...          ...   
203       0.0187       0.0346       0.0168       0.0177       0.0393   
204       0.0323       0.0101       0.0298       0.0564       0.0760   
205       0.0522       0.0437       0.0180       0.0292       0.0351   
206       0.0303       0.0353       0.0490       0.0608       0.0167   
207       0.0260       0.0363       0.0136       0.0272       0.0214   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0         0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1         0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2         0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3         0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4         0.0649       0.1209       0.2467       0.3564        0.4459  ...   
..           ...          ...          ...          ...           ...  ...   
203       0.1630       0.2028       0.1694       0.2328        0.2684  ...   
204       0.0958       0.0990       0.1018       0.1030        0.2154  ...   
205       0.1171       0.1257       0.1178       0.1258        0.2529  ...   
206       0.1354       0.1465       0.1123       0.1945        0.2354  ...   
207       0.0338       0.0655       0.1400       0.1843        0.2354  ...   

     attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0          0.0027        0.0065        0.0159        0.0072        0.0167   
1          0.0084        0.0089        0.0048        0.0094        0.0191   
2          0.0232        0.0166        0.0095        0.0180        0.0244   
3          0.0121        0.0036        0.0150        0.0085        0.0073   
4          0.0031        0.0054        0.0105        0.0110        0.0015   
..            ...           ...           ...           ...           ...   
203        0.0116        0.0098        0.0199        0.0033        0.0101   
204        0.0061        0.0093        0.0135        0.0063        0.0063   
205        0.0160        0.0029        0.0051        0.0062        0.0089   
206        0.0086        0.0046        0.0126        0.0036        0.0035   
207        0.0146        0.0129        0.0047        0.0039        0.0061   

     attribute_57  attribute_58  attribute_59  attribute_60  Class  
0          0.0180        0.0084        0.0090        0.0032   Rock  
1          0.0140        0.0049        0.0052        0.0044   Rock  
2          0.0316        0.0164        0.0095        0.0078   Rock  
3          0.0050        0.0044        0.0040        0.0117   Rock  
4          0.0072        0.0048        0.0107        0.0094   Rock  
..            ...           ...           ...           ...    ...  
203        0.0065        0.0115        0.0193        0.0157   Mine  
204        0.0034        0.0032        0.0062        0.0067   Mine  
205        0.0140        0.0138        0.0077        0.0031   Mine  
206        0.0034        0.0079        0.0036        0.0048   Mine  
207        0.0040        0.0036        0.0061        0.0115   Mine  

[208 rows x 61 columns]

In [7]:
sonar.info()
# index:208 dtype:float64(60), object(1) columns:61 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   attribute_1   208 non-null    float64
 1   attribute_2   208 non-null    float64
 2   attribute_3   208 non-null    float64
 3   attribute_4   208 non-null    float64
 4   attribute_5   208 non-null    float64
 5   attribute_6   208 non-null    float64
 6   attribute_7   208 non-null    float64
 7   attribute_8   208 non-null    float64
 8   attribute_9   208 non-null    float64
 9   attribute_10  208 non-null    float64
 10  attribute_11  208 non-null    float64
 11  attribute_12  208 non-null    float64
 12  attribute_13  208 non-null    float64
 13  attribute_14  208 non-null    float64
 14  attribute_15  208 non-null    float64
 15  attribute_16  208 non-null    float64
 16  attribute_17  208 non-null    float64
 17  attribute_18  208 non-null    float64
 18  attribute_19  208 non-null    

In [8]:
sonar.isnull().sum()

attribute_1     0
attribute_2     0
attribute_3     0
attribute_4     0
attribute_5     0
               ..
attribute_57    0
attribute_58    0
attribute_59    0
attribute_60    0
Class           0
Length: 61, dtype: int64

In [9]:
# 중복확인 
sonar[sonar.duplicated()]

Empty DataFrame
Columns: [attribute_1, attribute_2, attribute_3, attribute_4, attribute_5, attribute_6, attribute_7, attribute_8, attribute_9, attribute_10, attribute_11, attribute_12, attribute_13, attribute_14, attribute_15, attribute_16, attribute_17, attribute_18, attribute_19, attribute_20, attribute_21, attribute_22, attribute_23, attribute_24, attribute_25, attribute_26, attribute_27, attribute_28, attribute_29, attribute_30, attribute_31, attribute_32, attribute_33, attribute_34, attribute_35, attribute_36, attribute_37, attribute_38, attribute_39, attribute_40, attribute_41, attribute_42, attribute_43, attribute_44, attribute_45, attribute_46, attribute_47, attribute_48, attribute_49, attribute_50, attribute_51, attribute_52, attribute_53, attribute_54, attribute_55, attribute_56, attribute_57, attribute_58, attribute_59, attribute_60, Class]
Index: []

[0 rows x 61 columns]

In [10]:
sonar['Class'].value_counts()

Mine    111
Rock     97
Name: Class, dtype: int64

# 학습시키기 1

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [54]:
x = sonar.drop('Class', axis= 1)
y = sonar['Class']

In [55]:
# train 과 test를 x,y 로 쪼개서 확인 
# 학습시킬 문제 ,시험문제 , 학습시킬 문제에 대한 정답 , 시험문제에 대한 정답 
x_train, x_test, y_train, y_test = \
train_test_split(x,y, test_size = 0.1, stratify = y , random_state=0 )
#stratify에는 층 구분 변수이름을 입력 

In [56]:
model = LogisticRegression()

In [57]:
model

LogisticRegression()

In [58]:
model.fit(x_train, y_train)

LogisticRegression()

In [59]:
model.score(x_train, y_train)

0.8288770053475936

In [60]:
model.score(x_test, y_test)

0.8095238095238095

# 학습시키기 2

In [61]:
from sklearn.linear_model import LogisticRegressionCV

In [62]:
model2 = LogisticRegressionCV(max_iter= 1000, cv=10)

In [63]:
model2.fit(x_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

LogisticRegressionCV(cv=10, max_iter=1000)

In [64]:
model2.score(x_train, y_train)

0.839572192513369

In [65]:
model2.score(x_test, y_test)

0.7619047619047619

In [66]:
#1. 행번호(row number)로 선택하는 방법 (.iloc)
#2. label이나 조건표현으로 선택하는 방법 (.loc)
x_train.iloc[0].values

array([0.0392, 0.0108, 0.0267, 0.0257, 0.041 , 0.0491, 0.1053, 0.169 ,
       0.2105, 0.2471, 0.268 , 0.3049, 0.2863, 0.2294, 0.1165, 0.2127,
       0.2062, 0.2222, 0.3241, 0.433 , 0.5071, 0.5944, 0.7078, 0.7641,
       0.8878, 0.9711, 0.988 , 0.9812, 0.9464, 0.8542, 0.6457, 0.3397,
       0.3828, 0.3204, 0.1331, 0.044 , 0.1234, 0.203 , 0.1652, 0.1043,
       0.1066, 0.211 , 0.2417, 0.1631, 0.0769, 0.0723, 0.0912, 0.0812,
       0.0496, 0.0101, 0.0089, 0.0083, 0.008 , 0.0026, 0.0079, 0.0042,
       0.0071, 0.0044, 0.0022, 0.0014])

In [67]:
x_train.iloc[0].values.reshape(1,-1)

array([[0.0392, 0.0108, 0.0267, 0.0257, 0.041 , 0.0491, 0.1053, 0.169 ,
        0.2105, 0.2471, 0.268 , 0.3049, 0.2863, 0.2294, 0.1165, 0.2127,
        0.2062, 0.2222, 0.3241, 0.433 , 0.5071, 0.5944, 0.7078, 0.7641,
        0.8878, 0.9711, 0.988 , 0.9812, 0.9464, 0.8542, 0.6457, 0.3397,
        0.3828, 0.3204, 0.1331, 0.044 , 0.1234, 0.203 , 0.1652, 0.1043,
        0.1066, 0.211 , 0.2417, 0.1631, 0.0769, 0.0723, 0.0912, 0.0812,
        0.0496, 0.0101, 0.0089, 0.0083, 0.008 , 0.0026, 0.0079, 0.0042,
        0.0071, 0.0044, 0.0022, 0.0014]])

In [68]:
len(x_train.iloc[0].values)

60

In [69]:
x_train.iloc[0].values.reshape(1,60)

array([[0.0392, 0.0108, 0.0267, 0.0257, 0.041 , 0.0491, 0.1053, 0.169 ,
        0.2105, 0.2471, 0.268 , 0.3049, 0.2863, 0.2294, 0.1165, 0.2127,
        0.2062, 0.2222, 0.3241, 0.433 , 0.5071, 0.5944, 0.7078, 0.7641,
        0.8878, 0.9711, 0.988 , 0.9812, 0.9464, 0.8542, 0.6457, 0.3397,
        0.3828, 0.3204, 0.1331, 0.044 , 0.1234, 0.203 , 0.1652, 0.1043,
        0.1066, 0.211 , 0.2417, 0.1631, 0.0769, 0.0723, 0.0912, 0.0812,
        0.0496, 0.0101, 0.0089, 0.0083, 0.008 , 0.0026, 0.0079, 0.0042,
        0.0071, 0.0044, 0.0022, 0.0014]])

In [70]:
x_train.iloc[0].values.reshape(30,2)

array([[0.0392, 0.0108],
       [0.0267, 0.0257],
       [0.041 , 0.0491],
       [0.1053, 0.169 ],
       [0.2105, 0.2471],
       [0.268 , 0.3049],
       [0.2863, 0.2294],
       [0.1165, 0.2127],
       [0.2062, 0.2222],
       [0.3241, 0.433 ],
       [0.5071, 0.5944],
       [0.7078, 0.7641],
       [0.8878, 0.9711],
       [0.988 , 0.9812],
       [0.9464, 0.8542],
       [0.6457, 0.3397],
       [0.3828, 0.3204],
       [0.1331, 0.044 ],
       [0.1234, 0.203 ],
       [0.1652, 0.1043],
       [0.1066, 0.211 ],
       [0.2417, 0.1631],
       [0.0769, 0.0723],
       [0.0912, 0.0812],
       [0.0496, 0.0101],
       [0.0089, 0.0083],
       [0.008 , 0.0026],
       [0.0079, 0.0042],
       [0.0071, 0.0044],
       [0.0022, 0.0014]])

In [71]:
sensor = x_train.iloc[0].values.reshape(1,-1)

In [72]:
#모델이 훈련되면 predict()입력 값을 기반으로 출력 값을 예측하는 데 사용
model2.predict(sensor)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(


array(['Mine'], dtype=object)

In [73]:
y_train.iloc[0]

'Mine'

In [74]:
if model.predict(sensor) == 0 :
    print('mine 입니다')

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [75]:
for c in sonar.drop('Class', axis=1).columns :
    print(c)
    print(sonar[c].mean())
    print(sonar[c].median())
    print('-----')

attribute_1
0.029163942307692307
0.0228
-----
attribute_2
0.03843653846153848
0.0308
-----
attribute_3
0.04383221153846154
0.0343
-----
attribute_4
0.05389230769230771
0.04405
-----
attribute_5
0.07520240384615384
0.0625
-----
attribute_6
0.10457019230769235
0.09215000000000001
-----
attribute_7
0.1217466346153847
0.10694999999999999
-----
attribute_8
0.13479903846153843
0.1121
-----
attribute_9
0.17800288461538455
0.15225
-----
attribute_10
0.2082591346153846
0.1824
-----
attribute_11
0.2360129807692308
0.2248
-----
attribute_12
0.25022115384615395
0.24905
-----
attribute_13
0.2733052884615385
0.26395
-----
attribute_14
0.2965682692307692
0.2811
-----
attribute_15
0.32020144230769243
0.28169999999999995
-----
attribute_16
0.3784865384615385
0.30469999999999997
-----
attribute_17
0.4159831730769229
0.3084
-----
attribute_18
0.4523182692307695
0.3683
-----
attribute_19
0.5048115384615385
0.43495
-----
attribute_20
0.5630466346153848
0.5425
-----
attribute_21
0.609060096153846
0.61769999

In [76]:
sonar.describe()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
count   208.000000   208.000000   208.000000   208.000000   208.000000   
mean      0.029164     0.038437     0.043832     0.053892     0.075202   
std       0.022991     0.032960     0.038428     0.046528     0.055552   
min       0.001500     0.000600     0.001500     0.005800     0.006700   
25%       0.013350     0.016450     0.018950     0.024375     0.038050   
50%       0.022800     0.030800     0.034300     0.044050     0.062500   
75%       0.035550     0.047950     0.057950     0.064500     0.100275   
max       0.137100     0.233900     0.305900     0.426400     0.401000   

       attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
count   208.000000   208.000000   208.000000   208.000000    208.000000  ...   
mean      0.104570     0.121747     0.134799     0.178003      0.208259  ...   
std       0.059105     0.061788     0.085152     0.118387      0.134416  ...   
min       0.010200     0.003300     0.005500     0.007500      0.011300  ...   
25%       0.067025     0.080900     0.080425     0.097025      0.111275  ...   
50%       0.092150     0.106950     0.112100     0.152250      0.182400  ...   
75%       0.134125     0.154000     0.169600     0.233425      0.268700  ...   
max       0.382300     0.372900     0.459000     0.682800      0.710600  ...   

       attribute_51  attribute_52  attribute_53  attribute_54  attribute_55  \
count    208.000000    208.000000    208.000000    208.000000    208.000000   
mean       0.016069      0.013420      0.010709      0.010941      0.009290   
std        0.012008      0.009634      0.007060      0.007301      0.007088   
min        0.000000      0.000800      0.000500      0.001000      0.000600   
25%        0.008425      0.007275      0.005075      0.005375      0.004150   
50%        0.013900      0.011400      0.009550      0.009300      0.007500   
75%        0.020825      0.016725      0.014900      0.014500      0.012100   
max        0.100400      0.070900      0.039000      0.035200      0.044700   

       attribute_56  attribute_57  attribute_58  attribute_59  attribute_60  
count    208.000000    208.000000    208.000000    208.000000    208.000000  
mean       0.008222      0.007820      0.007949      0.007941      0.006507  
std        0.005736      0.005785      0.006470      0.006181      0.005031  
min        0.000400      0.000300      0.000300      0.000100      0.000600  
25%        0.004400      0.003700      0.003600      0.003675      0.003100  
50%        0.006850      0.005950      0.005800      0.006400      0.005300  
75%        0.010575      0.010425      0.010350      0.010325      0.008525  
max        0.039400      0.035500      0.044000      0.036400      0.043900  

[8 rows x 60 columns]

# 학습 시키기 3

In [77]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [78]:
scaler = StandardScaler()

In [79]:
x_train = scaler.fit_transform(x_train)
#x_train 을 sccaler 에 학습시켜서 transform 으로 각각 학습 
x_test = scaler.transform(x_test)
#본래의 x_test를 표준화 변화만 시킨거 

In [80]:
x_train

array([[ 0.43842592, -0.82597191, -0.43050828, ..., -0.55677057,
        -0.90845389, -0.99275199],
       [ 0.70074558,  0.41166228,  1.04312784, ..., -0.48133505,
        -0.43934248, -0.40089879],
       [ 0.35671979, -0.31004247, -0.52005214, ..., -0.40589954,
         0.07668006, -0.08524374],
       ...,
       [ 0.3782214 , -0.19969919, -0.0313985 , ..., -0.28520272,
        -0.5800759 , -0.22334282],
       [-0.7355621 ,  0.58761509,  0.48028071, ..., -0.11924459,
        -0.78335751,  1.4535746 ],
       [ 3.4314503 ,  2.66326183,  1.25547471, ...,  1.87225297,
         1.53092542,  2.42026817]])

In [81]:
model = LogisticRegression()

In [82]:
print(x_train.shape, y_train.shape)

(187, 60) (187,)


In [84]:
model.fit(x_train, y_train)

LogisticRegression()

In [85]:
model.score(x_train, y_train)

0.93048128342246

In [86]:
model.score(x_test, y_test)

0.8571428571428571

# 데이터 저장

In [88]:
import pickle 
# pickle : 저장 

In [89]:
scaler

StandardScaler()

In [90]:
# WITH OPEN ~ AS 어떠한 파일을 어떻게 하겠다 
# ('a','wb') a라는 파일을 wb 만들겠다 
with open ('scaler.pk2','wb') as f :
    pickle.dump(scaler, f)

In [91]:
with open('model.pk2','wb') as f :
    pickle.dump(model, f)