# 돌인지 지뢰인지 구분하는 시스템 만들기

In [3]:
import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')

In [4]:
real_data = pd.read_csv('sonar_csv.csv')

In [5]:
real_data.drop('Class', axis=1, inplace= True)

In [6]:
#1. 행번호(row number)로 선택하는 방법 (.iloc)
#2. label이나 조건표현으로 선택하는 방법 (.loc)
real = real_data.iloc[100].values

In [7]:
real.reshape(1,-1) #-1 맨뒤에서 부터 모두 불러오기 

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [18]:
real= real_data.iloc[100].values.reshape(1,-1)

In [19]:
real #학습시킬때 리스트 2개  똑같은 형식으로 만들어 줘야함 

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [20]:
#real= real_data.iloc[100].values

In [21]:
#real # 이건 리스트 1개 

# 데이터 불러오기

In [22]:
with open('scaler.pk2','rb') as f :
    scaler = pickle.load(f)

In [23]:
with open('model.pk2','rb') as f :
    model = pickle.load(f)

In [24]:
scaler

StandardScaler()

In [25]:
real = scaler.transform(real)

In [27]:
real

array([[ 1.45760232,  2.02804235,  2.79051232,  1.47085046,  1.20374041,
         0.21867894, -0.55612818, -0.50354609,  0.28402287,  1.17037029,
         2.42609876,  1.95526403,  1.693089  ,  1.4271479 ,  1.56287749,
         2.04135432,  2.08188897,  1.79104415,  1.07812508,  0.64553526,
         0.30433781, -0.94899655, -2.30218297, -2.61428527, -1.62808082,
        -1.71916968, -1.94187772, -2.09183337, -2.45401739, -1.44520973,
        -1.4227143 , -1.14129037, -0.79983194, -0.86004565, -0.45639379,
        -0.94880697, -1.08375359, -0.62902827, -0.70896902, -1.65635903,
        -0.92532905, -0.57528401, -0.62780339, -0.33693385, -0.80262332,
        -1.0989445 , -0.47598587, -0.20862248, -1.09597038, -1.01441939,
         0.80378794, -0.46053776,  2.31752009, -0.02060468,  0.59705417,
         1.85926403,  2.60017894, -0.36063823,  0.51451738,  1.31547551]])

In [31]:
predict = model.predict(real)[0]

In [32]:
predict

'Mine'

In [34]:
if predict == 'Mine' :
    print('지뢰가 나타났습니다. 돔황챠!!!!')
else :
    print('그냥 돌입니다. 쫄았냐? ㅎ ')

지뢰가 나타났습니다. 돔황챠!!!!
