In [1]:
import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')

In [2]:
real_data = pd.read_csv('sonar_csv.csv')

In [3]:
real_data.drop('Class', axis=1, inplace= True)

In [30]:
real = real_data.iloc[100].values # 100개의 데이터를 불러오는거 

In [48]:
real.reshape(1,-1)# -1 DATA전체 

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [28]:
real = real_data.iloc[100].values.reshape(1,-1) #학습시킬때 리스트 2개  똑같은 형식으로 만들어 줘야함 

In [27]:
real

array([0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
       0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
       0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
       0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
       0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
       0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
       0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
       0.023 , 0.0057, 0.0113, 0.0131])

In [29]:
real

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [19]:
# WITH OPEN ~ AS 저장한걸 불러오겠다 
with open('scaler.pkl','rb') as f :
    scaler = pickle.load(f)

In [20]:
with open('model.pk1','rb') as f :
    model = pickle.load(f)

In [45]:
scaler

StandardScaler()

In [21]:

real = scaler.transform(real)

In [22]:
predict = model.predict(real)[0]

In [23]:
if predict == 'Mine' :
    print('지뢰가 나타났습니다. 돔황챠')
else :
    print('그냥 돌입니다')

지뢰가 나타났습니다. 돔황챠
