In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('heart.csv')

In [3]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
data.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1    

In [5]:
data.shape

(303, 14)

In [6]:
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [7]:
data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

--

In [8]:
x = data.drop('target',axis =1)
y = data['target']

In [9]:
x_train, x_test, y_train, y_test = \
train_test_split(x,y, test_size=0.2,stratify = y, random_state=0)

In [10]:
model = LogisticRegression(max_iter= 1000)

In [11]:
model

LogisticRegression(max_iter=1000)

In [12]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [13]:
model.score(x_train, y_train)

0.8429752066115702

In [14]:
model.score(x_test, y_test)

0.8688524590163934

-

In [15]:
x_train, x_test, y_train, y_test = \
train_test_split(x,y, test_size=0.25,stratify = y, random_state=0)

In [16]:
for c in data.drop('target', axis=1).columns :
    print(c)
    print(data[c].mean()) 
    print(data[c].median())
    print('---------------')

age
54.366336633663366
55.0
---------------
sex
0.6831683168316832
1.0
---------------
cp
0.966996699669967
1.0
---------------
trestbps
131.62376237623764
130.0
---------------
chol
246.26402640264027
240.0
---------------
fbs
0.1485148514851485
0.0
---------------
restecg
0.528052805280528
1.0
---------------
thalach
149.64686468646866
153.0
---------------
exang
0.32673267326732675
0.0
---------------
oldpeak
1.0396039603960396
0.8
---------------
slope
1.3993399339933994
1.0
---------------
ca
0.7293729372937293
0.0
---------------
thal
2.3135313531353137
2.0
---------------


In [17]:
scaler = StandardScaler() 

In [18]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [19]:
x_train

array([[-1.35685398,  0.64026392,  1.95519993, ...,  0.96757589,
         1.20316371, -0.51208215],
       [ 0.40380828, -1.56185593, -0.93934605, ..., -0.6356338 ,
        -0.71345497, -0.51208215],
       [-0.36648146,  0.64026392,  0.99035127, ..., -0.6356338 ,
        -0.71345497, -0.51208215],
       ...,
       [ 1.17409801, -1.56185593, -0.93934605, ..., -0.6356338 ,
         2.16147306,  1.08028289],
       [-0.14639868,  0.64026392, -0.93934605, ..., -0.6356338 ,
         1.20316371,  1.08028289],
       [-0.36648146,  0.64026392,  0.99035127, ...,  0.96757589,
         0.24485437,  1.08028289]])

In [20]:
model2 = LogisticRegression(max_iter= 1000)

In [21]:
print(x_train.shape, y_train.shape)

(227, 13) (227,)


In [22]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
model.score(x_train, y_train)

0.8325991189427313

In [24]:
model.score(x_test, y_test)

0.868421052631579

--

In [25]:
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [26]:
x = data.drop('target',axis =1)
y = data['target']

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

In [28]:
pol = PolynomialFeatures(degree=2)

In [29]:
x = pol.fit_transform(x)

In [30]:
x_train,x_test,y_train,y_test = \
train_test_split(x,y, test_size=0.2,random_state=2)

In [31]:
model  = LogisticRegression()

In [32]:
model.fit(x_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
model.coef_ # w값

array([[ 2.53291436e-08,  6.48103856e-06, -1.35158120e-05,
         9.82598462e-06,  1.21904216e-05, -2.84447499e-05,
        -5.04851589e-07,  5.50415671e-06,  6.35309383e-06,
        -6.64178144e-06, -6.25029236e-06,  5.73051304e-06,
        -7.73151256e-06, -9.81441186e-06,  1.16434304e-03,
        -7.79166464e-04,  4.73905342e-04,  9.08048054e-04,
        -1.48863187e-04, -4.34428505e-05,  3.64147323e-04,
        -1.25723292e-03, -3.97111421e-04, -3.99011940e-04,
         3.53282707e-04, -4.74434028e-04, -4.88029827e-04,
        -1.35158120e-05, -7.04906711e-06, -1.71314148e-03,
        -3.58980748e-03, -4.35631675e-07, -1.40248233e-06,
        -1.93098803e-03, -6.08536495e-06, -1.34637809e-05,
        -1.70116108e-05, -1.05660858e-05, -3.36618543e-05,
         1.69282629e-05,  1.32672341e-03,  1.70849691e-03,
         1.37617211e-06,  1.04184340e-05,  1.53749458e-03,
         1.93659813e-06,  1.65365569e-05,  1.68241893e-05,
         1.39820743e-05,  1.87104953e-05, -4.27318395e-0

In [36]:
model.intercept_

array([2.53287549e-08])

In [37]:
model.score(x_test, y_test)

0.9016393442622951

In [38]:
model.score(x_train, y_train)

0.8471074380165289

In [42]:
import numpy as np

In [45]:
real = [35, 1, 2, 135, 240, 0, 0, 160, 1, 2.1, 1, 0, 1]

In [46]:
real= np.asarray(real).reshape(1,-1)

In [47]:
real = pol.transform(real)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


In [48]:
model.predict(real)

array([1], dtype=int64)